# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1468, 806)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayout = QtWidgets.QFormLayout(self.centralwidget)
        self.formLayout.setObjectName("formLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.PathStream = QtWidgets.QWidget(self.centralwidget)
        self.PathStream.setMinimumSize(QtCore.QSize(640, 480))
        self.PathStream.setMaximumSize(QtCore.QSize(640, 480))
        self.PathStream.setStyleSheet("background-color: rgb(0,128,0);")
        self.PathStream.setObjectName("PathStream")
        self.gridLayout.addWidget(self.PathStream, 0, 1, 1, 3)
        self.logText = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.logText.setMinimumSize(QtCore.QSize(640, 50))
        self.logText.setMaximumSize(QtCore.QSize(640, 480))
        self.logText.setReadOnly(True)
        self.logText.setObjectName("logText")
        self.gridLayout.addWidget(self.logText, 1, 0, 1, 1)
        self.eStop = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eStop.sizePolicy().hasHeightForWidth())
        self.eStop.setSizePolicy(sizePolicy)
        self.eStop.setMinimumSize(QtCore.QSize(128, 128))
        self.eStop.setMaximumSize(QtCore.QSize(256, 256))
        self.eStop.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/estop.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.eStop.setIcon(icon)
        self.eStop.setIconSize(QtCore.QSize(128, 128))
        self.eStop.setObjectName("eStop")
        self.gridLayout.addWidget(self.eStop, 1, 1, 1, 1)
        self.cStop = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cStop.sizePolicy().hasHeightForWidth())
        self.cStop.setSizePolicy(sizePolicy)
        self.cStop.setMinimumSize(QtCore.QSize(128, 128))
        self.cStop.setMaximumSize(QtCore.QSize(256, 256))
        self.cStop.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon/cstop.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cStop.setIcon(icon1)
        self.cStop.setIconSize(QtCore.QSize(128, 128))
        self.cStop.setObjectName("cStop")
        self.gridLayout.addWidget(self.cStop, 1, 2, 1, 1)
        self.Continue = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Continue.sizePolicy().hasHeightForWidth())
        self.Continue.setSizePolicy(sizePolicy)
        self.Continue.setMinimumSize(QtCore.QSize(128, 128))
        self.Continue.setMaximumSize(QtCore.QSize(256, 256))
        self.Continue.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icon/continue.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Continue.setIcon(icon2)
        self.Continue.setIconSize(QtCore.QSize(128, 128))
        self.Continue.setObjectName("Continue")
        self.gridLayout.addWidget(self.Continue, 1, 3, 1, 1)
        self.VideoStream = QtWidgets.QLabel(self.centralwidget)
        self.VideoStream.setMinimumSize(QtCore.QSize(640, 480))
        self.VideoStream.setMaximumSize(QtCore.QSize(640, 480))
        self.VideoStream.setStyleSheet("background-color: rgb(0, 0, 128);")
        self.VideoStream.setText("")
        self.VideoStream.setObjectName("VideoStream")
        self.gridLayout.addWidget(self.VideoStream, 0, 0, 1, 1)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.logText.setPlainText(_translate("MainWindow", "Logs\n"
""))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
